---


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<center>

## **Karter Couser**

Graduate student

kcou8702@students.vsu.edu

</center>

<br>

**Education** 

Virginia State University Master's of Science in biology Anticipated Graduation: Spring:2023 GPA: 3.8 

<br>

**RELEVANT RESEARCH EXPERIENCE:**

●	2022-2023 Dr. Chris Roh, Dr. Anthony Hay “Seed dispersal” Cornell University Ithaca, New York

●	2021-2022 Thesis Work: Dr. Siddiqui, Dr. Rafie, Dr. H. Li, “A study on the anticancer property of blueberry in human liver cancer cells” Virginia State University, Petersburg, VA

●	2018-2019 Dr. Cobb-Abdullah “Analyzing the Accumulation, of cadmium absorbed in plant tissue” Virginia Union University, Richmond, VA

●	2018-2019 Dr. Jackson “Portion Control: Analyzing heat and volume Variations in Copper Nanoparticles”, Virginia Union University, Richmond, VA

●	2016 - Dr. Jackson “Analyzing the antibacterial properties of Nanoparticles doped in MOFs”,Virginia Union University, Richmond, VA


<br>

**POSTER PRESENTATIONS:**
<br>
●April 2022, Association of Research Directors (ARD) Oral Presentation, Atlanta, Georgia, 
“Effect of Cultivation Conditions on Blueberry (Vaccinium Corymbosum) Polyphenolic Contents and Characterization of their Anticancer Effects on Hepatic Cancer Cells.”

●April 2022, Black in Physiology Conference Poster Presentation, Virtual 
“Air pollution Effects on Prenatal Neurological Development.”

●April 2019 American Chemical Society Undergraduate Research Poster Session, Orlando, Florida “Analyzing the Accumulation, of cadmium absorbed in plant tissue”.

●April 2018 and 2019 American Chemical Society Undergraduate Research Poster Session, University of Virginia, Charlottesville, VA. “Portion Control: Analyzing heat and volume Variations in Copper Nanoparticles”. Dr. K. Jackson.

●November 2018 Annual Biomedical Research Conference for Minority Students, Indianapolis Convention Center, Indianapolis, Indiana. “Analyzing the Accumulation of cadmium absorbed in plant tissue”.

●April 2018 Research and Creative Inquiry, Virginia Union University, “Portion Control: Analyzing heat and volume Variations in Copper Nanoparticles”.

●April 2016 American Chemical Society Undergraduate Research Poster Session, University of Virginia, Charlottesville, VA. Jackson “Analyzing the effects of eugenol and caffeine of freshwater Fish”. 

<br>

**MOST RECENT WORK HISTORY:**

● Aug 2022- May 2023 Cornell University- Thomas Wyatt Turner Fellow/
Graduate Research Assistant

● Aug 2021- Dec 2022 Virginia State University – Graduate Research
Assistant/TA

● Oct 2020-July2022 Next Molecular Analytics – Molecular lab - Laboratory Analysts

● Dec 2019- July 2021 Pharmaceutical Product Development- Assistant
Scientist working in Vaccines

● July 2019-Sept 2022 IEH Institute for Environmental Health- Microbiology Lab Analyst

● May 2016-Aug 2019 Virginia Union University- Lab Tech/Research

<br>

**Volunteer**

-2021-2022 Community Garden –Coordinator and garden manager, The Light Community Church

-2018-2020 Small Farms community garden- Volunteer- Virginia State University

-2017-2019 Jobs for Life- Mentor and instructor – The Light Community Church 





